# Generated by Django 3.2.6 on 2021-08-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='xRay',
            new_name='xRayy',
        ),
    ]
