# Generated by Django 3.2.6 on 2021-08-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_rename_xray_xrayy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xrayy',
            old_name='img',
            new_name='xray_img',
        ),
    ]
