# Generated by Django 3.2.6 on 2021-08-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_rename_img_xrayy_xray_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayy',
            name='output_one',
            field=models.ImageField(blank=True, default='', null=True, upload_to='output/'),
        ),
        migrations.AddField(
            model_name='xrayy',
            name='output_two',
            field=models.ImageField(blank=True, default='', null=True, upload_to='output/'),
        ),
    ]
