# Generated by Django 3.2.6 on 2021-08-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_auto_20210820_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xrayy',
            name='output_two',
        ),
    ]
